[package]
authors = ["Hrvoje Bandov <hrvoje.bandov@gmail.com>"]
edition = "2018"
name = "lunatic"
version = "0.1.0"

[dependencies]
anyhow = "1.0.41"
tokio = { version = "1", features = ["full"] }
wasmtime = "0.28.0"
